apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  labels:
    app: my-python-app
spec:
  replicas: 2  # You can change this number based on your desired scale
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: 050752605171.dkr.ecr.ap-south-1.amazonaws.com/my-python-app:v2.0.0  # Replace with your ECR image URL and version
        ports:
        - containerPort: 5000  # Exposing port 5000 inside the container

---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service
spec:
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the LoadBalancer
      targetPort: 5000  # The port inside the container to be exposed
  type: LoadBalancer  # The service type that creates a LoadBalancer
